### ISSUE TITLE
As a player I want to be able to select a field to shoot at in order to sink ships and preferably win the game.

### ISSUE THREAD

**Issue by Nickschlaedde** [sopra-fs23-group-11/sopra-fs23-group-11-server#4]
Acceptance criteria:
- [x] When selecting a field, said field should be shot.
- [x] Only one field can be shot per round.
- [x] After shooting, the opponent gets to select a field and shoot.

Development tasks:
- [x] sopra-fs23-group-11/sopra-fs23-group-11-client#18
- [x] sopra-fs23-group-11/sopra-fs23-group-11-client#19
- [x] #84
- [x] #85
- [x] #86

**Comment by Olabi98** [comment]
some tasks were deleted/ replaced by either defining other functionality which satisfy the purpose or doing it using websockets (#6 seems to be deleted)
